apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-io2
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  fsType: xfs
  DiskIOPSReadWrite: "100"



