apiVersion: v1
kind: ConfigMap
metadata:
  name: magic8ball-configmap
data:
  AZURE_OPENAI_ENDPOINT: $AZURE_OPENAI_ENDPOINT
  AZURE_OPENAI_DEPLOYMENT: $AZURE_OPENAI_DEPLOYMENT
  WORKLOAD_IDENTITY_CLIENT_ID: $WORKLOAD_IDENTITY_CLIENT_ID
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic8ball
  labels:
    app.kubernetes.io/name: magic8ball
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: magic8ball
  template:
    metadata:
      labels:
        app.kubernetes.io/name: magic8ball
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: magic8ball-sa
      containers:
      - name: magic8ball
        image: $IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef: 
            name: magic8ball-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: magic8ball
spec:
  selector:
    app.kubernetes.io/name: magic8ball
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: magic8ball-sa
  annotations:
    azure.workload.identity/client-id: $WORKLOAD_IDENTITY_CLIENT_ID
    azure.workload.identity/tenant-id: $TENANT_ID
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magic8ball
  annotations:
    cert-manager.io/issuer: letsencrypt-dev
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - $HOSTNAME
    secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: magic8ball
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $EMAIL
    privateKeySecretRef:
      name: tls-secret
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx