apiVersion: v1
kind: ConfigMap
metadata:
  name: magic8ball-configmap
data:
  AZURE_OPENAI_ENDPOINT: $AZURE_OPENAI_ENDPOINT
  AZURE_OPENAI_MODEL: $AZURE_OPENAI_MODEL
  AZURE_OPENAI_DEPLOYMENT: $AZURE_OPENAI_MODEL
  AZURE_OPENAI_VERSION: $AZURE_OPENAI_VERSION
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic8ball
  labels:
    app.kubernetes.io/name: magic8ball
    azure.workload.identity/use: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: magic8ball
  template:
    metadata:
      labels:
        app.kubernetes.io/name: magic8ball
    spec:
      serviceAccountName: magic8ball-sa
      containers:
      - name: magic8ball
        image: $IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef: 
            name: magic8ball-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: magic8ball-service
spec:
  selector:
    app.kubernetes.io/name: magic8ball
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: magic8ball-sa
  annotations:
    azure.workload.identity/client-id: $WORKLOAD_IDENTITY_CLIENT_ID