apiVersion: v1
kind: ConfigMap
metadata:
  name: magic8ball-configmap
  namespace: magic8ball
data:
  TITLE: "Magic 8 Ball"
  LABEL: "Pose your question and cross your fingers!"
  TEMPERATURE: "0.9"
  IMAGE_WIDTH: "80"
  AZURE_OPENAI_TYPE: azure_ad
  AZURE_OPENAI_BASE: https://myopenai.openai.azure.com/
  AZURE_OPENAI_MODEL: gpt-35-turbo
  AZURE_OPENAI_DEPLOYMENT: magic8ballGPT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic8ball
  namespace: magic8ball
  labels:
    app.kubernetes.io/name: magic8ball
    azure.workload.identity/use: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: magic8ball
  template:
    metadata:
      labels:
        app.kubernetes.io/name: magic8ball
    spec:
      containers:
      - name: magic8ball
        image: $IMAGE
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef: 
            name: magic8ball-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: magic8ball-service
  namespace: magic8ball
spec:
  selector:
    app.kubernetes.io/name: magic8ball
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: magic8ball-service-account
  namespace: magic8ball
  annotations:
    azure.workload.identity/client-id: $WORKLOAD_MANAGED_IDENTITY_CLIENT_ID
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magic8ball-ingress
  namespace: ingress-nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - magic8ball.contoso.com
    secretName: tls-secret
  rules:
  - host: magic8ball.contoso.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: magic8ball
            port:
              number: 8501
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $EMAIL
    privateKeySecretRef:
      name: tls-secret
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx